apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            - sh
            - -c
            - until nc -z userservice-redis-service 6379; do echo "Esperando pelo Redis..."; sleep 2; done;    
      containers:
      - name: eventservice
        image: pedromartins70/eventservice:latest 
        ports:
        - containerPort: 5002
        env:
          - name: DB_HOST
            value: "eventservice-db-service"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "eventservice_user"
          - name: DB_PASSWORD
            value: "eventservice_pass"
          - name: DB_NAME
            value: "eventservice_db"
        volumeMounts:
          - name: eventservice-images
            mountPath: /usr/src/app/public/uploads/event_pictures
      volumes:
        - name: eventservice-images
          persistentVolumeClaim:
            claimName: eventservice-images-pvc
