apiVersion: v1
kind: Service
metadata:
  name: locationservice
  labels:
    app: locationservice
spec:
  selector:
    app: locationservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5005     
      targetPort: 5005 