apiVersion: v1
kind: Service
metadata:
  name: userineventservice
  labels:
    app: userineventservice
spec:
  selector:
    app: userineventservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5003        
      targetPort: 5003  