apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-notifications
  template:
    metadata:
      labels:
        app: worker-notifications
    spec:
      containers:
        - name: worker-notifications
          image: a23893/workerRabbitMQQ:latest 
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq:5672"
