# PersistentVolume para armazenar os dados do PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: location-pv-volume
  labels:
    type: local
    app: locationservice-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/locationservice-db" 

---
# PersistentVolumeClaim para utilizar o PV acima
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: location-pv-claim
  labels:
    app: locationservice-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
