apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  selector:
    app: userservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001        
      targetPort: 5001  